name: Vercel Production Deployment

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    name: Trigger Vercel Deploy Hook
    runs-on: ubuntu-latest
    steps:
      - name: Send Deploy Trigger to Vercel
        run: |
          curl -X POST -s -S "${{ secrets.VERCEL_DEPLOY_HOOK }}"
